version: '3.8'

services:
  zetmem-server:
    build: .
    ports:
      - "8080:8080"
      - "9092:9090"  # Metrics port
    environment:
      - ZETMEM_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMADB_HOST=http://chromadb:8000
      - ZETMEM_LOG_LEVEL=debug
    volumes:
      - ./config:/app/config
      - ./prompts:/app/prompts
      - ./data:/app/data
    depends_on:
      - chromadb
      - redis
    networks:
      - zetmem-network
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8004:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    networks:
      - zetmem-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - zetmem-network
    restart: unless-stopped

  # Optional: RabbitMQ for future evolution worker
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=zetmem
      - RABBITMQ_DEFAULT_PASS=zetmem_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - zetmem-network
    restart: unless-stopped

  # Sentence Transformers embedding service
  sentence-transformers:
    build:
      context: ./docker/sentence-transformers
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    environment:
      - MODEL_NAME=all-MiniLM-L6-v2
      - MAX_BATCH_SIZE=32
    volumes:
      - sentence_transformers_cache:/root/.cache
    networks:
      - zetmem-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - zetmem-network
    restart: unless-stopped

volumes:
  chromadb_data:
  redis_data:
  rabbitmq_data:
  prometheus_data:
  sentence_transformers_cache:

networks:
  zetmem-network:
    driver: bridge
